from enum import StrEnum

class SymbolState(StrEnum):
    DISCOVERED = "DISCOVERED"
    WATCHING = "WATCHING"
    ARMED = "ARMED"
    ENTRY_PENDING = "ENTRY_PENDING"
    POSITION_OPEN = "POSITION_OPEN"
    MANAGING = "MANAGING"
    EXIT_PENDING = "EXIT_PENDING"
    EXITED = "EXITED"
    COOLDOWN = "COOLDOWN"

